apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata: # kpt-merge: /trigger
  name: trigger
spec:
  pipelineSpec:
    tasks:
    - name: nos-triggers
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:nuxeo/nos-jx-make.d/tekton/tasks/jenkins-trigger.yaml@versionStream
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
        - name: jx-variables
        - name: trigger
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h0m0s
status: {}
