apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr
    context: "pr"
    always_run: true
    optional: false
    trigger: "/test"
    rerun_command: "/retest"
    source: "jenkins-trigger.yaml"
  postsubmits:
  - name: master
    context: "master"
    source: "jenkins-trigger.yaml"
    branches:
    - ^master$
  - name: release
    context: "release"
    source: "jenkins-trigger.yaml"
    branches:
    - ^v[0-9]+.[0-9]+.[0-9]+$
